# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 881512f68d3c19d18e41a1d6eac1950f1c39b9b65b7a482c5689cbca394eeba4f0da7ac3c8982e2c0f499bc2dcd1c72f981f97bafcab22d7a1a0d5e01c6ef9af

test:
  secret_key_base: 5e887e570aa604bd175cb1489a4b9d6e04b3df19551751b2832520e3ae51d57f6ad334d5a782f009ae6f3d82cad61e756bb76b7ae2c8ccdcec22f11f8ad2ff2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
